### ISSUE TITLE
再次点击take a photo，不会删除之前的

### ISSUE THREAD

**Issue by unssnu** [Fi2zz/vue-camera#1]
这个插件非常棒，在ios真机上试了，很方便就调出系统相机

但是有个问题，我开启了预览功能后，上传一张图片，再次点击按钮，不会删除之前那张，会累加
另外，调节预览的camera-preview类好像也木有作用。。。
请教大神，该如何解决这两个问题呢？十分感谢~！

**Comment by Fi2zz** [comment]
@unssnu 另外，调节预览的camera-preview类好像也木有作用。。。 
这个需要你手动设置样式
